version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false

  static:
    build: ./src/static_service
    environment:
      - ADDR=0.0.0.0:3000
    labels:
      - traefik.http.routers.static.entrypoints=http
      - traefik.http.routers.static.rule=PathPrefix(`/static`)
      - traefik.http.middlewares.staticprefix.stripprefix.prefixes=/static
      - traefik.http.routers.static.middlewares=staticprefix@docker
      - traefik.http.services.static.loadbalancer.server.port=3000
    ports:
      - 3000

  status:
    build: ./src/status_service
    environment:
      - ADDR=0.0.0.0:3001
      - "SERVICES=Static=http://static:3000 Index=http://index:3002 Upload=http://upload:3003 Certification=http://cert:3004"
    labels:
      - traefik.http.routers.status.entrypoints=http
      - traefik.http.routers.status.rule=PathPrefix(`/status`)
      - traefik.http.middlewares.statusprefix.stripprefix.prefixes=/status
      - traefik.http.routers.status.middlewares=statusprefix@docker
      - traefik.http.services.status.loadbalancer.server.port=3001
    ports:
      - 3001

  index:
    build: ./src/index_service
    environment:
      - ADDR=0.0.0.0:3002
    labels:
      - traefik.http.routers.index.entrypoints=http
      - traefik.http.routers.index.rule=PathPrefix(`/`)
      - traefik.http.services.index.loadbalancer.server.port=3002
    ports:
      - 3002

  upload:
    build: ./src/upload_service
    environment:
      - ADDR=0.0.0.0:3003
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    labels:
      - traefik.http.routers.upload.entrypoints=http
      - traefik.http.routers.upload.rule=PathPrefix(`/upload`)
      - traefik.http.middlewares.uploadprefix.stripprefix.prefixes=/upload
      - traefik.http.routers.upload.middlewares=uploadprefix@docker
      - traefik.http.services.upload.loadbalancer.server.port=3003
    ports:
      - 3003

  cert:
    build: ./src/cert_service
    environment:
      - ADDR=0.0.0.0:3004
      - PRIVATE_KEY=/usr/certs/key.pem
    labels:
      - traefik.http.routers.cert.entrypoints=http
      - traefik.http.routers.cert.rule=PathPrefix(`/cert`)
      - traefik.http.middlewares.certprefix.stripprefix.prefixes=/cert
      - traefik.http.routers.cert.middlewares=certprefix@docker
      - traefik.http.services.cert.loadbalancer.server.port=3004
    ports:
      - 3004
