[package]
name = "sign_service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
lazy_static = "1.4.0"
openssl = "0.10"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tera = "1"
tokio = { version = "1.0", features = ["full"] }
